mission:
  header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: ''
  name: "Waterloo Park Path Loop"
  uuid: "8f57fd20-8a8c-4748-85ef-be1495b3ee06"
  waypoints:
    -
      name: "Waypoint: 1"
      uuid: "3edcedd7-ae0d-47cf-bd23-f7988d2779b7"
      latitude: 43.468105
      longitude: -80.529903
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 2"
      uuid: "ad23202e-7067-4f1c-8677-2dc07af1e729"
      latitude: 43.468158
      longitude: -80.530049
      heading: -1.0
      tasks:
        -
          name: "Wait"
          uuid: "ec1121a8-7481-420f-b532-c47ea86afcd7"
          action_server_name: "/wait"
          version: "0.0.0"
          floats: [5.0]
          strings: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 3"
      uuid: "fe452e77-4a26-41b0-b4ab-ee1859612a60"
      latitude: 43.468437
      longitude: -80.530339
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 4"
      uuid: "5ed54c1f-1599-497a-9c16-93c7ca6c355e"
      latitude: 43.468614
      longitude: -80.530583
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 5"
      uuid: "2e021345-636b-4bd3-81ba-4f6901fdc016"
      latitude: 43.468806
      longitude: -80.530718
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 6"
      uuid: "00c041ee-2ca4-40ba-8e38-65ac900d5a1d"
      latitude: 43.468655
      longitude: -80.530811
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 7"
      uuid: "a5826fc5-b696-4b63-82aa-cc2e7a426640"
      latitude: 43.468753
      longitude: -80.530915
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 8"
      uuid: "7ff204b2-79a3-46da-a8c0-2c734b4c5314"
      latitude: 43.468697
      longitude: -80.531070
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 9"
      uuid: "03d2f14b-9b4b-4131-8cd3-34e7b65e9649"
      latitude: 43.468637
      longitude: -80.531190
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 10"
      uuid: "f3e62921-7f0d-4ff8-8b99-270936490da4"
      latitude: 43.468525
      longitude: -80.531352
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 11"
      uuid: "e7c2542e-7413-495c-b765-9013d292981f"
      latitude: 43.468457
      longitude: -80.531421
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 12"
      uuid: "ffdb54e9-f4a5-433d-b9c1-e9d06d363624"
      latitude: 43.468303
      longitude: -80.531461
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 13"
      uuid: "3d012fb0-ced2-443f-b84a-0f6c27f5cec9"
      latitude: 43.468221
      longitude: -80.531501
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 14"
      uuid: "85d36dd6-1a8e-46e6-bca7-3ef0ea88467c"
      latitude: 43.467857
      longitude: -80.531525
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 15"
      uuid: "55598cee-e774-4b94-80a1-900961b5d6c9"
      latitude: 43.467526
      longitude: -80.531421
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 16"
      uuid: "2c90552e-c847-4c7a-9786-b8d032b93b35"
      latitude: 43.467431
      longitude: -80.531318
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 17"
      uuid: "92cae0fe-3bed-4776-a268-823bf5ce6f98"
      latitude: 43.467299
      longitude: -80.531030
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 18"
      uuid: "842417f7-2674-481c-924e-a11a3bc510eb"
      latitude: 43.467100
      longitude: -80.530620
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 19"
      uuid: "57372482-4629-47b4-8d64-43c8987b283d"
      latitude: 43.467075
      longitude: -80.530420
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 20"
      uuid: "215ae18d-45f3-43d1-ae99-55df1b17a7b2"
      latitude: 43.467134
      longitude: -80.530371
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 21"
      uuid: "903b3b72-c988-425c-b962-37eda1d44309"
      latitude: 43.467503
      longitude: -80.529732
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 22"
      uuid: "ae54f4f2-f771-4577-82cd-01d7bddc144f"
      latitude: 43.467586
      longitude: -80.529714
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 23"
      uuid: "14dc289c-936a-49ab-b5a2-e983170558d6"
      latitude: 43.467749
      longitude: -80.529875
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
  onav_config: "To be determined"
