mission:
  header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: ''
  name: "Waterloo Park Path Loop"
  uuid: "8f57fd20-8a8c-4748-85ef-be1495b3ee06"
  waypoints:
    -
      name: "Waypoint: 1"
      uuid: "3edcedd7-ae0d-47cf-bd23-f7988d2779b7"
      latitude: 43.468105
      longitude: -80.529903
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 2"
      uuid: "14dc289c-936a-49ab-b5a2-e983170558d6"
      latitude: 43.468140
      longitude: -80.529917
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 3"
      uuid: "ad23202e-7067-4f1c-8677-2dc07af1e729"
      latitude: 43.468130
      longitude: -80.530123
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 4"
      uuid: "fe452e77-4a26-41b0-b4ab-ee1859612a60"
      latitude: 43.467997
      longitude: -80.530399
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 5"
      uuid: "5ed54c1f-1599-497a-9c16-93c7ca6c355e"
      latitude: 43.467880
      longitude: -80.530561
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 6"
      uuid: "2e021345-636b-4bd3-81ba-4f6901fdc016"
      latitude: 43.467765
      longitude: -80.530800
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 7"
      uuid: "00c041ee-2ca4-40ba-8e38-65ac900d5a1d"
      latitude: 43.468003
      longitude: -80.531069
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 8"
      uuid: "a5826fc5-b696-4b63-82aa-cc2e7a426640"
      latitude: 43.467977
      longitude: -80.531431
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 9"
      uuid: "7ff204b2-79a3-46da-a8c0-2c734b4c5314"
      latitude: 43.468202
      longitude: -80.531411
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 10"
      uuid: "03d2f14b-9b4b-4131-8cd3-34e7b65e9649"
      latitude: 43.468375
      longitude: -80.531296
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 11"
      uuid: "f3e62921-7f0d-4ff8-8b99-270936490da4"
      latitude: 43.468410
      longitude: -80.530884
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 12"
      uuid: "e7c2542e-7413-495c-b765-9013d292981f"
      latitude: 43.468467
      longitude: -80.530816
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 13"
      uuid: "ffdb54e9-f4a5-433d-b9c1-e9d06d363624"
      latitude: 43.468473
      longitude: -80.530503
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 14"
      uuid: "3d012fb0-ced2-443f-b84a-0f6c27f5cec9"
      latitude: 43.468518
      longitude: -80.530223
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 15"
      uuid: "85d36dd6-1a8e-46e6-bca7-3ef0ea88467c"
      latitude: 43.468590
      longitude: -80.529995
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 16"
      uuid: "55598cee-e774-4b94-80a1-900961b5d6c9"
      latitude: 43.468455
      longitude: -80.529759
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 17"
      uuid: "2c90552e-c847-4c7a-9786-b8d032b93b35"
      latitude: 43.468262
      longitude: -80.529821
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
  onav_config: "To be determined"
