mission: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  name: "loop_ccw"
  uuid: "03d2f14b-9b4b-4131-8cd3-34e7b65e9649"
  waypoints: 
    - 
      name: "Waypoint: 73"
      uuid: "f3e62921-7f0d-4ff8-8b99-270936490da4"
      latitude: 50.1094659
      longitude: -97.31933051
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 74"
      uuid: "e7c2542e-7413-495c-b765-9013d292981f"
      latitude: 50.109554727894995
      longitude: -97.31935733209015
      heading: -1.0
      tasks: 
        - 
          name: "Wait"
          uuid: "ffdb54e9-f4a5-433d-b9c1-e9d06d363624"
          action_server_name: "/wait"
          version: "0.0.0"
          floats: [1.0]
          strings: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 75"
      uuid: "3d012fb0-ced2-443f-b84a-0f6c27f5cec9"
      latitude: 50.10957834643285
      longitude: -97.31949787982616
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 76"
      uuid: "85d36dd6-1a8e-46e6-bca7-3ef0ea88467c"
      latitude: 50.109546139346946
      longitude: -97.3196437919802
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 77"
      uuid: "55598cee-e774-4b94-80a1-900961b5d6c9"
      latitude: 50.10949138727634
      longitude: -97.31967705139654
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 78"
      uuid: "2c90552e-c847-4c7a-9786-b8d032b93b35"
      latitude: 50.10943174778163
      longitude: -97.31964729684084
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 79"
      uuid: "92cae0fe-3bed-4776-a268-823bf5ce6f98"
      latitude: 50.10940779614299
      longitude: -97.31958085815336
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 80"
      uuid: "842417f7-2674-481c-924e-a11a3bc510eb"
      latitude: 50.10939075901827
      longitude: -97.31947033807134
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 81"
      uuid: "57372482-4629-47b4-8d64-43c8987b283d"
      latitude: 50.1093957332199
      longitude: -97.31938048253424
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 82"
      uuid: "215ae18d-45f3-43d1-ae99-55df1b17a7b2"
      latitude: 50.10942168544136
      longitude: -97.31934074572256
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 83"
      uuid: "903b3b72-c988-425c-b962-37eda1d44309"
      latitude: 50.10945139724599
      longitude: -97.31933015577467
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
  onav_config: "To be determined"
