mission: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  name: "loop_cw"
  uuid: "97d04525-401f-4205-8035-41967e07d00c"
  waypoints: 
    - 
      name: "Waypoint: 84"
      uuid: "85555a3f-dc56-4dce-b428-24aa098680d9"
      latitude: 50.10946596
      longitude: -97.31933051
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 85"
      uuid: "c9fb4fe4-1d5a-4b5d-a795-ae394d9ed6d2"
      latitude: 50.10951205043854
      longitude: -97.31931663193738
      heading: -1.0
      tasks: 
        - 
          name: "Wait"
          uuid: "a2c0a716-a97f-42a8-beb8-b620d5714e9e"
          action_server_name: "/wait"
          version: "0.0.0"
          floats: [1.0]
          strings: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 86"
      uuid: "5708e650-f764-4275-ac17-80f6975a465c"
      latitude: 50.10951048212147
      longitude: -97.31928058384105
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 87"
      uuid: "83421b68-a92d-462e-b46c-806d236d4147"
      latitude: 50.109492446550036
      longitude: -97.31925315593256
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 88"
      uuid: "5f5f746b-20aa-4ade-b644-1771a1802e3e"
      latitude: 50.10945951201136
      longitude: -97.31924610302985
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 89"
      uuid: "ceb089bc-0703-42ab-b473-e186f676b395"
      latitude: 50.109424225012056
      longitude: -97.31924610302985
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 90"
      uuid: "04203c14-58ff-4e0f-8f35-e5595bae3800"
      latitude: 50.10940775772776
      longitude: -97.31927823285355
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 91"
      uuid: "14dc289c-936a-49ab-b5a2-e983170558d6"
      latitude: 50.10942736161626
      longitude: -97.3193213338526
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    - 
      name: "Waypoint: 92"
      uuid: "ae54f4f2-f771-4577-82cd-01d7bddc144f"
      latitude: 50.10945679202118
      longitude: -97.31932963889967
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
  onav_config: "To be determined"
