#! /usr/bin/env python3

from cpr_onav_api_examples_lib.ros_node import RosNode
from cpr_onav_api_examples_lib.yaml_config import YamlConfig
import time
import os

# The file containing the mission configuration (adjust as needed)
MISSION_YAML_FILE = os.environ.get("HOME", "administrator") + "/example_ws/src/" + \
                   "CPR-OutdoorNav/src/cpr_onav_api_examples/config/sample_mission.yaml"

class MissionFromYamlFile(RosNode):
    """
    Create and run a mission loaded from a YAML configuration file.
    Be sure to place the robot near the start point (50.109508, -97.318985)
    prior to starting the mission.
    """

    def __init__(self):
        """Initialize the mission details and server connection."""

        RosNode.__init__(self, 'mission_from_yaml_file')
        self.mission = YamlConfig.yamlFileToMission(MISSION_YAML_FILE)

        # NOTE: to save the configuration to file, uncomment the following lines:
        # YamlConfig.missionToYamlFile('/tmp/test1.yaml', self.mission)

    def run(self):
        """Execute the mission."""

        if not self.mission.startMission():
            return False
        while not self.mission.isMissionComplete():
            time.sleep(1.0)
        return self.mission.getMissionSuccess()


if __name__ == '__main__':
    if MissionFromYamlFile().run():
        print("Mission completed successfully")
    else:
        print("Mission failed")
