#! /usr/bin/env python3

from cpr_onav_api_examples_lib.ros_node import RosNode
from cpr_onav_api_examples_lib.waypoint import Waypoint
from cpr_onav_api_examples_lib.mission import Mission
import time


class SimpleMission2(RosNode):
    """Create and run a simple mission with 2 waypoints.

    Our goal is to set up two waypoints, Waypoint A at (50.1095255, -97.3192484)
    and Waypoint B at (50.1094938, -97.3191085), then create a mission such
    that the robot drives to Waypoint A, then to Waypoint B.

    The coordinates used in this example are based on the cpr_agriculture_gazebo
    world and should be updated to match the location in which the user's
    robot will be operating.
    """

    def __init__(self):
        """Initialize the mission details and server connection."""

        RosNode.__init__(self, 'simple_mission_2')
        waypoints = [
            Waypoint("A", "uuid-waypoint-3", 50.1095255, -97.3192484),
            Waypoint("B", "uuid-waypoint-1", 50.1094938, -97.3191085),
        ]
        self.mission = Mission("Mission 2", "uuid-mission-2", waypoints)


    def run(self):
        """Execute the mission."""

        if not self.mission.startMission():
            return False
        while not self.mission.isMissionComplete():
            time.sleep(1.0)
        return self.mission.getMissionSuccess()


if __name__ == '__main__':
    if SimpleMission2().run():
        print("Mission completed successfully")
    else:
        print("Mission failed")
