mission:
  header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: ''
  name: "Sample Mission"
  uuid: "8f57fd20-8a8c-4748-85ef-be1495b3ee06"
  waypoints:
    -
      name: "Waypoint: 60"
      uuid: "3edcedd7-ae0d-47cf-bd23-f7988d2779b7"
      latitude: 50.10950820165676
      longitude: -97.31898507913323
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 61"
      uuid: "ad23202e-7067-4f1c-8677-2dc07af1e729"
      latitude: 50.1095698924641
      longitude: -97.31929487427445
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 62"
      uuid: "fe452e77-4a26-41b0-b4ab-ee1859612a60"
      latitude: 50.109437123117864
      longitude: -97.31946787675591
      heading: -1.0
      tasks:
        -
          name: "Wait"
          uuid: "ec1121a8-7481-420f-b532-c47ea86afcd7"
          action_server_name: "/wait"
          version: "0.0.0"
          floats: [3.0]
          strings: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 63"
      uuid: "5ed54c1f-1599-497a-9c16-93c7ca6c355e"
      latitude: 50.109384820042074
      longitude: -97.3194477601883
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 64"
      uuid: "2e021345-636b-4bd3-81ba-4f6901fdc016"
      latitude: 50.10934056359333
      longitude: -97.31936192949982
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 65"
      uuid: "00c041ee-2ca4-40ba-8e38-65ac900d5a1d"
      latitude: 50.10946930962604
      longitude: -97.31921709021302
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 66"
      uuid: "a5826fc5-b696-4b63-82aa-cc2e7a426640"
      latitude: 50.10949344950718
      longitude: -97.31911382516594
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
    -
      name: "Waypoint: 67"
      uuid: "7ff204b2-79a3-46da-a8c0-2c734b4c5314"
      latitude: 50.10949613171619
      longitude: -97.31898910244675
      heading: -1.0
      tasks: []
      position_tolerance: -1.0
      yaw_tolerance: -1.0
  onav_config: "To be determined"
